/*
 * Copyright 2019, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.fsct.android.appportaria.cpf

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProvider
import androidx.navigation.fragment.findNavController
import com.fsct.android.appportaria.R
import com.fsct.android.appportaria.database.RegistroDatabase
import com.fsct.android.appportaria.databinding.FragmentCpfBinding

/**
 * Fragment that displays a list of clickable icons,
 * each representing a sleep quality rating.
 * Once the user taps an icon, the quality is set in the current evento
 * and the database is updated.
 */
class CpfFragment : Fragment() {

    /**
     * Called when the Fragment is ready to display content to the screen.
     *
     * This function uses DataBindingUtil to inflate R.layout.fragment_sleep_quality.
     *
     * It is also responsible for passing the [CpfViewModel] to the
     * [FragmentCpfBinding] generated by DataBinding. This will allow DataBinding
     * to use the [LiveData] on our ViewModel.
     */
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {

        // Get a reference to the binding object and inflate the fragment views.
        val binding: FragmentCpfBinding = DataBindingUtil.inflate(
                inflater, R.layout.fragment_cpf, container, false)

        val application = requireNotNull(this.activity).application
        val arguments = CpfFragmentArgs.fromBundle(requireArguments())

        // Create an instance of the ViewModel Factory.
        val dataSource = RegistroDatabase.getInstance(application).registroDatabaseDao
        val viewModelFactory = CpfViewModelFactory(arguments.registroKey, dataSource)

        // Get a reference to the ViewModel associated with this fragment.
        val cpfViewModel =
                ViewModelProvider(
                        this, viewModelFactory).get(CpfViewModel::class.java)

        // To use the View Model with data binding, you have to explicitly
        // give the binding object a reference to it.
        binding.cpfViewModel = cpfViewModel

        // Add an Observer to the state variable for Navigating when a Quality icon is tapped.
        cpfViewModel.navigateToRegentrada.observe(viewLifecycleOwner, Observer {
            if (it == true) { // Observed state is true.
                this.findNavController().navigate(
                        CpfFragmentDirections.actionCpfFragmentToRegentradaFragment())
                // Reset state to make sure we only navigate once, even if the device
                // has a configuration change.
                cpfViewModel.doneNavigating()
            }
        })

        return binding.root
    }
}
